dist: trusty
sudo: required
language: cpp
compiler:
  - gcc
addons:
  apt:
    packages:
      - qtbase5-dev
      - libuchardet-dev
before_script:
  - curl -L -o '/tmp/cmake-install.sh' 'https://cmake.org/files/v3.9/cmake-3.9.6-Linux-x86_64.sh'
  - sudo sh /tmp/cmake-install.sh --prefix=/usr/local --exclude-subdir --skip-license
  - curl -L -o '/tmp/libarchive.zip' 'https://github.com/libarchive/libarchive/archive/v3.3.2.zip'
  - unzip -d '/tmp' '/tmp/libarchive.zip'
  - cd '/tmp/libarchive-3.3.2'
  - cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_TEST=OFF
  - make -j
  - sudo make install
  - cd -
script:
  - cmake .
  - make -j
