dist: trusty
sudo: required
language: cpp
compiler:
  - gcc
addons:
  apt:
    packages:
      - qtbase5-dev
before_script:
  - curl -L -o '/tmp/cmake-install.sh' 'https://cmake.org/files/v3.9/cmake-3.9.6-Linux-x86_64.sh'
  - sudo sh /tmp/cmake-install.sh --prefix=/usr/local --exclude-subdir --skip-license
script:
  - cmake .
  - make -j
